### ISSUE TITLE
Creation and collision mapping of push-able box

### ISSUE THREAD

**Issue by faizazaza** [Faiza-Maghrabi/FoxPuzzle#19]
May be used for certain puzzles

A box that can be pushed - could inhert movement vectors from player on collision?
https://www.youtube.com/watch?v=3BOn2gs7z04 perhaps

fine to move to final milestone if too much

**Comment by nbal21388** [comment]
PLAYER CAN PUSH OBJECT - done in TESTPushObjects scene
