### ISSUE TITLE
Data persistance

### ISSUE THREAD

**Issue by hazalDK** [Faiza-Maghrabi/FoxPuzzle#37]
We need to make sure that data is persisted without duplicating the items when loading in different scenes (entering the houses) 
Below is a tutorial that might help: (I've done the tutorial just not sure if it works yet)
https://www.youtube.com/watch?v=hzdADY2LkJU

**Comment by faizazaza** [comment]
Should wait til https://github.com/Faiza-Maghrabi/FoxPuzzle/issues/25 is completed
