### ISSUE TITLE
Intro Cutscene

### ISSUE THREAD

**Issue by faizazaza** [Faiza-Maghrabi/FoxPuzzle#59]
Opening cutscene that introduces the plot
Could include words but a talking fox is kinda wacky

Was thinking something like the camera pans over the fox cubs and we somehow show they are hungry
Could be done via a tummy rumble sound effect or maybe a thought bubble with food?
Fox walks out of the den and into the OpenScene

**Comment by hazalDK** [comment]
Make the cub animation, just need it to sit down and have tails wagging.
https://sketchfab.com/3d-models/low-poly-fox-d99158951c634f6cb52eab920ffb55eb - child fox asset needs to be added as well
