### ISSUE TITLE
Add/Create Food Models

### ISSUE THREAD

**Issue by faizazaza** [Faiza-Maghrabi/FoxPuzzle#60]
Add in models for food 
Either from the unity store, other sites or via blender

**Comment by nbal21388** [comment]
Task completed.

There are a total of 12 foods. 
We have Chicken, Pizza, Burger, A5 Wagyu Steak, Cooked Steak, Croissant, Toast, Cheese, Tomato, Watermelon, Maki and Tempura.

Food prefabs are in the Assets/Prefabs/FoodPrefabs directory.
Food icons are in the Assets/ImportedModels/FREE Food Pack/Textures directory.
The FoodList file in the StreamingAssets/FoodList directory is also updated to reflect the new food prefabs.

![Screenshot 2024-12-29 181957](https://github.com/user-attachments/assets/52809412-0830-4496-88e9-fb7dac704165)
